In [0]:
import torch

# Tensores
---

In [0]:
# Tensor con dimensiones dadas de números aleatorios
A = torch.randn((8, 3, 5))

In [3]:
# Tamaño de un tensor
A.size()

torch.Size([8, 3, 5])

In [4]:
# Tensor.size() funciona como una tupla
A.size() == (8, 3, 5)

True

In [5]:
# Los tensores soportan slicing
A[0, :, 0]

tensor([-0.5127, -0.5526,  1.4915])

In [6]:
# torch.zeros devuelve un tensor de la forma especificado con puros ceros
C = torch.zeros((5, 5))
C.dtype

torch.float32

In [7]:
# torch.randint recibe opcional un minimo, un maximo y un size para devolver un
#   tensor con valores enteros aleatorios en el rango
D = torch.randint(2, (5, 5))
D

tensor([[1, 1, 0, 1, 0],
        [1, 1, 0, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 1, 1],
        [0, 0, 1, 0, 1]])

In [8]:
C.dtype, D.dtype

(torch.float32, torch.int64)

In [9]:
# Tensor.float() convierte a floats los valores del tensor
C + D == C + D.float()

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [0]:
# Configurar el tipo por defecto de los tensores creados a flotantes
torch.set_default_tensor_type('torch.FloatTensor')

In [11]:
# En qué dispositivo está el tensor: CPU/GPU
C.device

device(type='cpu')

In [12]:
# ¿Está disponible la GPU?
torch.cuda.is_available()

True

In [0]:
# Dispositivo a usar
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [14]:
device

device(type='cuda')

In [0]:
x = torch.randn((3, 5)) # CPU

# torch.ones_like(Tensor) crea un tensor con puros unos de la misma forma 
#   que el tensor pasado
y = torch.ones_like(x, device=device) # GPU

In [16]:
# Error porque no están en el mismo dispositivo
x + y

RuntimeError: ignored

In [18]:
# Para poder hacer operaciones convertimos al mismo dispositivo con to()
x = x.to(device)
z = x + y
print(z)

tensor([[-0.1272, -0.1770,  0.4930,  0.4073,  1.2342],
        [ 0.1771,  1.5688,  1.9755,  1.1847,  0.1610],
        [ 0.8900,  0.9086,  1.7225, -0.7804, -0.1015]], device='cuda:0')


In [19]:
print(z.cpu())

tensor([[-0.1272, -0.1770,  0.4930,  0.4073,  1.2342],
        [ 0.1771,  1.5688,  1.9755,  1.1847,  0.1610],
        [ 0.8900,  0.9086,  1.7225, -0.7804, -0.1015]])


(tensor([[-0.1272, -0.1770,  0.4930,  0.4073,  1.2342],
         [ 0.1771,  1.5688,  1.9755,  1.1847,  0.1610],
         [ 0.8900,  0.9086,  1.7225, -0.7804, -0.1015]], device='cuda:0'),
 tensor([[-0.1272, -0.1770,  0.4930,  0.4073,  1.2342],
         [ 0.1771,  1.5688,  1.9755,  1.1847,  0.1610],
         [ 0.8900,  0.9086,  1.7225, -0.7804, -0.1015]]))

# Datasets
---

In [21]:
from google.colab import drive
drive.mount('/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /gdrive


In [0]:
# torchvision tiene datasets relacionados con imagenes
from torchvision import datasets

In [24]:
# Datasets en torchvision
dir(datasets)

['CIFAR10',
 'CIFAR100',
 'Caltech101',
 'Caltech256',
 'CelebA',
 'Cityscapes',
 'CocoCaptions',
 'CocoDetection',
 'DatasetFolder',
 'EMNIST',
 'FakeData',
 'FashionMNIST',
 'Flickr30k',
 'Flickr8k',
 'HMDB51',
 'ImageFolder',
 'ImageNet',
 'KMNIST',
 'Kinetics400',
 'LSUN',
 'LSUNClass',
 'MNIST',
 'Omniglot',
 'PhotoTour',
 'QMNIST',
 'SBDataset',
 'SBU',
 'SEMEION',
 'STL10',
 'SVHN',
 'UCF101',
 'USPS',
 'VOCDetection',
 'VOCSegmentation',
 'VisionDataset',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'caltech',
 'celeba',
 'cifar',
 'cityscapes',
 'coco',
 'fakedata',
 'flickr',
 'folder',
 'hmdb51',
 'imagenet',
 'kinetics',
 'lsun',
 'mnist',
 'omniglot',
 'phototour',
 'sbd',
 'sbu',
 'semeion',
 'stl10',
 'svhn',
 'ucf101',
 'usps',
 'utils',
 'video_utils',
 'vision',
 'voc']

In [26]:
# Descarga el dataset CIFAR10 en la ruta especificada.
#   Lo descarga porque download=True
cifar = datasets.CIFAR10('/gdrive/My Drive/dl-pytorch/datasets', download=True)


Extracting /gdrive/My Drive/dl-pytorch/datasets/cifar-10-python.tar.gz to /gdrive/My Drive/dl-pytorch/datasets


In [29]:
len(cifar) # Numero de ejemplos

50000

In [0]:
# Datos del dataset CIFAR10 en un tensor
data = torch.Tensor(cifar.data)

In [48]:
# Proporciones del dataset (imagenes son tensores de cuatro dimensiones)
data.size()

torch.Size([50000, 32, 32, 3])